import { FETCH_CAT_REQUEST, FETCH_CAT_SUCCESS, FETCH_CAT_ERROR, DELETE_CAT_REQUEST, DELETE_CAT_SUCCESS, DELETE_CAT_ERROR } from './cat';
import { FETCH_DOG_REQUEST, FETCH_DOG_SUCCESS, FETCH_DOG_ERROR, DELETE_DOG_REQUEST, DELETE_DOG_SUCCESS, DELETE_DOG_ERROR } from './dog';


export { FETCH_CAT_REQUEST, FETCH_CAT_SUCCESS, FETCH_CAT_ERROR, DELETE_CAT_REQUEST, DELETE_CAT_SUCCESS, DELETE_CAT_ERROR, FETCH_DOG_REQUEST, FETCH_DOG_SUCCESS, FETCH_DOG_ERROR, DELETE_DOG_REQUEST, DELETE_DOG_SUCCESS, DELETE_DOG_ERROR };

